### ISSUE TITLE
Initialize Shutter system contracts

### ISSUE THREAD

**Issue by fredo** [shutter-network/optimism#12]
The shutter contracts are predeployed in the genesis file. However, they are not initialized.

In order to let a devnet run we need to send certain transactions in order to initialize the contracts, so they the keyper set starts running. 

In production the dao will need to send those transactions.

- Pass a public address which is controlled by us as the default admin
- KeyperSetContract
  - Deploy a KeyperSetContract
  - Set Threshold
  - Set KeyBroadcaster
  - Add Keypers to the contract
  - finalize
  - broadcast eon key
  - schedule keyper set in keyper set manager
- Set withdraw role in Inbox

**Comment by fredo** [comment]
this is done? @ezdac

**Comment by ezdac** [comment]
This is done.
