### ISSUE TITLE
Connect to shutter p2p and listen to decryption key

### ISSUE THREAD

**Issue by fredo** [shutter-network/optimism#2]
We decided to outsource the key listening process into its own application. 

The main reason for it is, to keep the diff to the original op-node small as we need to maintain it. The application must 

- [ ] connect to p2p network and listen to decryption keys
- [ ] connect to op-geth to be able to read the state via the standard JSON RPC interface
- [ ] once a decryption key is received for the next block, validate with respect to eon key broadcast on chain and current keyper set

The decryption key must be forwarded to the op-node app. This can be done either by pushing, polling or long-polling by the op-node.
Thus, the op-node app needs to implement this mechanism.

@ezdac any preferences regarding the inter process comms?

**Comment by jannikluhn** [comment]
> If shutter is inactive, do we change/require the connection to the p2p network and do we still listen for keys or do we completely shut the connection off?

It's probably easier to just keep listening, I don't see a big downside. There could be a configuration option for the sequencer to turn it off though in case it's deactivated for a long time, or not activated yet.

An alternative way of implementing this could be an external application (the "decryption key listener") which communicates the keys to op-geth via an RPC interface. The keys could either be pushed by the listener or pulled when needed (or long-polled or subscribed to) by `op-node`. A potential advantage of this design is that it probably requires fewer changes to `op-node`, but it depends on the exact architecture which I'm not sure about yet.

**Comment by fredo** [comment]
A discussion with max which I had yesterday resulted in, that we should keep in mind of the modularity concept of the OP stack. So ideally with our implementation we should try to minimize the modification surface in op-node so that it's easy to plug in/out. Whether that's achievable is a different topic but should be included in our design descisions

**Comment by fredo** [comment]
> An alternative way of implementing this could be an external application (the "decryption key listener") which communicates the keys to op-geth via an RPC interface. The keys could either be pushed by the listener or pulled when needed (or long-polled or subscribed to) by op-node. A potential advantage of this design is that it probably requires fewer changes to op-node, but it depends on the exact architecture which I'm not sure about yet.

The nice upside about this idea would be that Optimism could continue to run regardless of the availability of the keyper network. 

Even switching to another keyper set network.
